# Generated by Django 6.0.5 on 2026-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_produit_options_produit_date_ajout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='lien_affiliation',
            field=models.URLField(max_length=1000),
        ),
    ]
