# Generated by Django 6.0.5 on 2026-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_produit_description_remove_produit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='coup_de_coeur',
            field=models.BooleanField(default=False, verbose_name='Afficher dans les Coups de Cœur'),
        ),
    ]
