# Generated by Django 6.0.5 on 2026-06-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_produit_coup_de_coeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='lien_affiliation',
            new_name='url_affiliation',
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.produit')),
            ],
        ),
    ]
