# Generated by Django 6.0.5 on 2026-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_lien_affiliation_produit_url_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
